### ISSUE TITLE
Need help?

### ISSUE THREAD

**Issue by ezerw** [vsquared-apps/go-weather#4]
Hi, I'm looking for projects to contribute and found this one. Do you need help with it? any plan for how this CLI should work?

**Comment by vince-fugnitto** [comment]
> Hi, I'm looking for projects to contribute and found this one. Do you need help with it? any plan for how this CLI should work?

@ezerw thank you for your interest, at the moment there is no detailed plan for the project.
It is a currently a side project between friends to learn and try golang.
